databases:
  - name: social_media_db
    plan: free
    databaseName: social_media
    user: social_media_user

services:
  - type: web
    plan: free
    name: social_media_api
    runtime: python
    # buildCommand: 'cd social_media_api && ./build.sh'
    buildCommand: 'cd social_media_api && chmod +x build.sh && ./build.sh'
    # startCommand: 'cd social_media_api && python -m gunicorn social_media_api.asgi:application -k uvicorn.workers.UvicornWorker'
    startCommand: 'cd social_media_api && python -m gunicorn social_media_api.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: social_media_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DEBUG
        value: "False"
      # - key: ALLOWED_HOSTS
      #   value: ".onrender.com"
      # - key: PYTHON_VERSION
      #   value: "3.9.0"