databases:
  - name: social_medial_db
    plan: free
    databaseName: social_media
    user: topzee

services:
  - type: web
    plan: free
    name: social_media_api
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn social_media_api.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: social_medial_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      # - key: DEBUG
      #   value: "False"
      # - key: ALLOWED_HOSTS
      #   value: ".onrender.com"
      # - key: PYTHON_VERSION
      #   value: "3.9.0"